spring:
  application:
    name: cloud-storage
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  data:
    redis:
      port: ${SPRING_DATA_REDIS_PORT}
      host: ${SPRING_DATA_REDIS_HOST}
server:
  error:
    whitelabel:
      enabled: false
  port: 8080

logging:
  level:
    org.springframework.security: INFO

minio:
  username: ${MINIO_USERNAME}
  password: ${MINIO_PASSWORD}
  url: ${MINIO_URL}
  bucket-name: ${MINIO_BUCKET_NAME}