spring:
  application:
    name: cloud-storage
  datasource:
    url: jdbc:postgresql://host.docker.internal:5430/cloud_storage_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  data:
    redis:
      port: 6379
      host: localhost
server:
  error:
    whitelabel:
      enabled: false
  port: 8080

logging:
  level:
    org.springframework.security: INFO

minio:
  username: minioadmin
  password: minioadmin
  url: http://localhost:9000
  bucket-name: user-files